[package]
name = "zoomtest"
version = "2.0.1"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[dependencies]
num = "*"
nalgebra = "*"
rand = "*"
itertools = "*"
crossbeam = "*"
zoom = "1.1.0"
glium = "0.13.3"
glowygraph = "0.2.1"
