[package]
name = "zoomtest"
version = "1.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[dependencies]
num = "*"
nalgebra = "*"
rand = "*"
itertools = "*"
crossbeam = "*"
kiss3d = {git = "https://github.com/Ticki/kiss3d"}
zoom = {git = "https://github.com/vadixidav/zoom.git"}
