[package]
name = "zoomtest"
version = "2.2.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[dependencies]
num = "0.1.30"
nalgebra = "0.5.1"
rand = "0.3.13"
itertools = "0.4.7"
crossbeam = "0.2.4"
zoom = "1.1.0"
glium = "0.13.3"
glowygraph = "0.3.0"
